INSERT IGNORE INTO tipos_mascotas (nombre) VALUES
                                        ('Perro'),
                                        ('Gato'),
                                        ('Pájaro'),
                                        ('Conejo'),
                                        ('Hamster'),
                                        ('Tortuga'),
                                        ('Iguana'),
                                        ('Pez'),
                                        ('Cobaya'),
                                        ('Hurón');

-- Insertar razas para cada tipo de mascota si no existen
INSERT IGNORE INTO razas (nombre, tipo_mascota_id) VALUES
-- Razas de Perro
    ('Shih Tzu', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Schnauzer', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Labrador Retriever', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Golden Retriever', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Bulldog', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Poodle', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Chihuahua', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Pug', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Dálmata', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
    ('Boxer', (SELECT id FROM tipos_mascotas WHERE nombre = 'Perro')),
-- Razas de Gato
    ('Siamés', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Persa', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Bengala', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Maine Coon', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Ragdoll', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('British Shorthair', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Scottish Fold', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Munchkin', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Siberiano', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
    ('Sphynx', (SELECT id FROM tipos_mascotas WHERE nombre = 'Gato')),
-- Razas de Pájaro
    ('Canario', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Periquito', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Loro', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Cacatúa', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Papagayo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Agapornis', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Ninfa', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Diamante Mandarín', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Cotorra', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
    ('Tórtola', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pájaro')),
-- Razas de Conejo
    ('Holandés Enano', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Belier', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Rex', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Lionhead', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Flemish Giant', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Mini Lop', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Angora', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Chinchilla', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Holland Lop', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
    ('Mini Rex', (SELECT id FROM tipos_mascotas WHERE nombre = 'Conejo')),
-- Razas de Hamster
    ('Sirio', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Ruso', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Roborovski', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Chino', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Dorado', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Campbell', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Siberiano', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Anão', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Teddy Bear', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
    ('Campbells', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hamster')),
-- Razas de Tortuga
    ('Griega', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Rusa', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Leopardo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Africana', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Pavo Real', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Pintada', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Caja', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Pescuezo Largo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('Orejas Rojas', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
    ('De Florida', (SELECT id FROM tipos_mascotas WHERE nombre = 'Tortuga')),
-- Razas de Iguana
    ('Común', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Verde', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Rinoceronte', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Negra', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Azul', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Raya Espinosa', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Patas de Hacha', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Cresta', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Caimán', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
    ('Escarabajo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Iguana')),
-- Razas de Pez
    ('Guppy', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Betta', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Cíclido', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Goldfish', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Neón', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Koi', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Pez Globo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Killi', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Sardina', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
    ('Pez Ángel', (SELECT id FROM tipos_mascotas WHERE nombre = 'Pez')),
-- Razas de Cobaya
    ('Peruviana', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Abisinia', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Americana', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Coronet', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Teddy', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Peruano de Pelo Corto', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Skinny', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Texel', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Sheltie', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
    ('Peruano de Pelo Largo', (SELECT id FROM tipos_mascotas WHERE nombre = 'Cobaya')),
-- Razas de Hurón
    ('Albino', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Sable', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Blanco', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Chocolate', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Panda', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Polecat', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Canela', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Sable Oscuro', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Panda Chocolate', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón')),
    ('Blanco Sable', (SELECT id FROM tipos_mascotas WHERE nombre = 'Hurón'));

-- Insertar usuario admin

-- Insertar consejos
INSERT INTO Consejos (texto, edad, peso, alimentacion, raza_id) VALUES
-- Consejos para razas de Perro
('Los Shih Tzu son propensos a problemas en los ojos debido a su estructura facial, así que mantén sus ojos limpios y revisa cualquier signo de irritación.', 'Adulto', 4.5, 'Alimento de calidad para razas pequeñas', 1),
('Los Schnauzer pueden ser territoriales, así que socialízalos desde cachorros para evitar comportamientos agresivos.', 'Cachorro', 6.2, 'Alimento específico para su tamaño y edad', 2),
('Los Labrador Retriever son muy activos y necesitan mucho ejercicio para mantenerse sanos y felices.', 'Adulto', 30.0, 'Alimento balanceado para razas grandes', 3),
('Los Golden Retriever son propensos a problemas de cadera, así que mantén un peso saludable y evita el sobreesfuerzo durante su crecimiento.', 'Cachorro', 25.0, 'Alimento de calidad para razas grandes', 4),
('Los Bulldogs pueden tener problemas respiratorios debido a su estructura facial, así que evita el ejercicio intenso en climas calurosos y mantén un peso saludable.', 'Adulto', 23.0, 'Alimento específico para razas braquicéfalas', 5),
('Los Poodle son inteligentes y fáciles de entrenar, así que asegúrate de proporcionarles estimulación mental junto con ejercicio físico.', 'Adulto', 7.0, 'Alimento de calidad para razas medianas', 6),
('Los Chihuahuas son pequeños pero tienen mucha energía, así que proporciónales ejercicio diario y no los sobreprotejas.', 'Adulto', 2.0, 'Alimento específico para razas pequeñas', 7),
('Los Pug son propensos a la obesidad, así que controla su alimentación y asegúrate de que hagan suficiente ejercicio.', 'Adulto', 6.5, 'Alimento balanceado para razas pequeñas', 8),
('Los Dálmatas son enérgicos y necesitan mucho ejercicio para evitar el aburrimiento y comportamientos destructivos.', 'Adulto', 25.0, 'Alimento de calidad para razas medianas', 9),
('Los Boxers son juguetones y pueden ser un poco tercos en el entrenamiento, así que sé paciente y consistente en tu enfoque de entrenamiento.', 'Cachorro', 20.0, 'Alimento específico para razas medianas', 10),

-- Consejos para razas de Gato
('Los Siameses son vocales y necesitan interacción humana, así que asegúrate de pasar tiempo de calidad con ellos todos los días.', 'Adulto', 4.0, 'Alimento de calidad para razas activas', 11),
('Los Persas tienen pelaje largo que requiere cepillado regular para evitar enredos y formación de bolas de pelo.', 'Adulto', 5.0, 'Alimento específico para razas de pelo largo', 12),
('Los Bengalas son muy activos y les gusta jugar, así que asegúrate de proporcionarles juguetes y enriquecimiento ambiental.', 'Cachorro', 6.0, 'Alimento balanceado para razas activas', 13),
('Los Maine Coon son grandes y pueden necesitar dietas específicas para controlar su peso, así que consulta con tu veterinario sobre sus necesidades dietéticas.', 'Adulto', 8.0, 'Alimento de calidad para razas grandes', 14),
('Los Ragdolls son conocidos por ser tranquilos y cariñosos, así que asegúrate de darles mucho amor y atención.', 'Adulto', 5.5, 'Alimento balanceado para razas de interior', 15),
('Los British Shorthair son propensos a la obesidad, así que controla su alimentación y fomenta el ejercicio diario.', 'Adulto', 7.5, 'Alimento específico para razas de interior', 16),
('Los Scottish Fold tienen orejas dobladas que requieren cuidado especial para prevenir infecciones y problemas de salud.', 'Adulto', 6.0, 'Alimento de calidad para razas de interior', 17),
('Los Munchkin tienen patas cortas que pueden causar problemas de espalda, así que evita que salten desde alturas elevadas.', 'Adulto', 4.0, 'Alimento específico para razas pequeñas', 18),
('Los Siberianos tienen un pelaje denso que puede requerir cepillado regular para evitar la formación de bolas de pelo.', 'Adulto', 6.0, 'Alimento balanceado para razas medianas', 19),
('Los Sphynx son sin pelo y pueden ser sensibles al frío, así que asegúrate de mantenerlos abrigados en climas más fríos.', 'Adulto', 3.0, 'Alimento de calidad para razas sin pelo', 20),

-- Consejos para razas de Pájaro
('Los Canarios son pájaros cantores y disfrutan de la interacción auditiva, así que habla y canta con ellos para estimularlos.', 'Adulto', 0.03, 'Semillas, frutas y verduras frescas', 21),
('Los Periquitos son sociales y les gusta la compañía, así que asegúrate de pasar tiempo interactuando con ellos todos los días.', 'Adulto', 0.04, 'Mezcla de semillas específica para periquitos', 22),
('Los Loros son inteligentes y necesitan estimulación mental, así que proporciónales juguetes y juegos de enriquecimiento.', 'Adulto', 0.5, 'Mezcla de semillas de alta calidad y frutas y verduras frescas', 23),
('Las Cacatúas son juguetonas y pueden necesitar mucha interacción y entretenimiento para evitar el aburrimiento.', 'Adulto', 0.6, 'Mezcla de semillas, pellets y frutas y verduras frescas', 24),
('Los Papagayos son muy inteligentes y pueden aprender trucos y palabras, así que dedica tiempo a entrenarlos y socializarlos.', 'Adulto', 0.7, 'Mezcla de semillas, pellets y frutas y verduras frescas', 25),
('Los Agapornis son monógamos y pueden deprimirse si se quedan solos, así que asegúrate de proporcionarles compañía o considera tener una pareja para ellos.', 'Adulto', 0.05, 'Mezcla de semillas específica para agapornis y frutas y verduras frescas', 26),
('Las Ninfas son activas y les gusta volar, así que proporciona un ambiente seguro para que puedan estirar sus alas.', 'Adulto', 0.06, 'Mezcla de semillas específica para ninfas y frutas y verduras frescas', 27),
('Los Diamantes Mandarín son pequeños y pueden estresarse fácilmente con el manejo excesivo, así que respeta su espacio y observa desde la distancia.', 'Adulto', 0.02, 'Mezcla de semillas específica para diamantes mandarín y frutas y verduras frescas', 28),
('Las Cotorras son sociables y les gusta la interacción, así que proporciónales juguetes y actividades para mantenerlos ocupados.', 'Adulto', 0.5, 'Mezcla de semillas específica para cotorras y frutas y verduras frescas', 29),
('Las Tórtolas son tímidas y pueden necesitar tiempo para aclimatarse a un nuevo entorno, así que sé paciente y tranquilo al acercarte a ellas.', 'Adulto', 0.1, 'Mezcla de semillas específica para tórtolas y frutas y verduras frescas', 30),

-- Consejos para razas de Conejo
('Los Holandeses Enanos son activos y necesitan mucho espacio para correr y explorar, así que proporciona un ambiente enriquecido para ellos.', 'Adulto', 1.0, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 31),
('Los Belier son propensos a problemas dentales, así que asegúrate de proporcionarles heno y juguetes para roer para mantener sus dientes sanos.', 'Adulto', 1.5, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 32),
('Los Rex tienen pelaje suave que puede enredarse fácilmente, así que cepíllalos regularmente para evitar nudos y enredos.', 'Adulto', 1.2, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 33),
('Los Lionhead tienen una melena distintiva que requiere cuidado regular para mantenerla limpia y libre de enredos, así que cepíllalos con frecuencia.', 'Adulto', 1.3, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 34),
('Los Flemish Giant son grandes y necesitan mucho espacio para moverse, así que proporciona un área grande y segura para que puedan explorar.', 'Adulto', 5.0, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 35),
('Los Mini Lop son juguetones y pueden disfrutar de juguetes interactivos y actividades para mantenerse estimulados.', 'Adulto', 1.4, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 36),
('Los Angora tienen pelaje largo que requiere cepillado regular para evitar enredos y formación de bolas de pelo.', 'Adulto', 1.5, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 37),
('Las Chinchillas son nocturnas y necesitan un lugar tranquilo y oscuro para dormir durante el día.', 'Adulto', 0.5, 'Heno de alta calidad, verduras frescas y pellets específicos para chinchillas', 38),
('Los Holland Lop son cariñosos y pueden disfrutar del tiempo de juego y la interacción con sus cuidadores.', 'Adulto', 1.3, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 39),
('Los Mini Rex tienen pelaje corto y denso que requiere poco mantenimiento, así que cepíllalos ocasionalmente para eliminar el pelo suelto.', 'Adulto', 1.2, 'Heno de alta calidad, verduras frescas y pellets específicos para conejos', 40),

-- Consejos para razas de Hurón
('Los Hurones Albinos son sensibles a la luz brillante, así que proporciona áreas sombreadas y refugios oscuros en su jaula.', 'Adulto', 1.0, 'Alimento específico para hurones', 41),
('Los Hurones Sable son curiosos y pueden meterse en lugares estrechos, así que asegúrate de que su área de juego esté seguro y libre de peligros.', 'Adulto', 1.2, 'Alimento específico para hurones', 42),
('Los Hurones Blancos son propensos a la obesidad, así que controla su alimentación y proporciona oportunidades para el ejercicio diario.', 'Adulto', 1.1, 'Alimento específico para hurones', 43),
('Los Hurones Chocolate son juguetones y pueden disfrutar de juguetes interactivos y tiempo de juego con sus cuidadores.', 'Adulto', 1.3, 'Alimento específico para hurones', 44),
('Los Hurones Panda tienen un pelaje distintivo que requiere cuidado regular para evitar enredos y problemas de piel, así que cepíllalos con frecuencia.', 'Adulto', 1.2, 'Alimento específico para hurones', 45),
('Los Hurones Polecat son activos y necesitan mucho ejercicio para mantenerse sanos y felices, así que proporciónales oportunidades para correr y explorar.', 'Adulto', 1.1, 'Alimento específico para hurones', 46),
('Los Hurones Canela son curiosos y pueden disfrutar de juguetes que estimulen su mente, como rompecabezas de comida y juguetes de búsqueda.', 'Adulto', 1.0, 'Alimento específico para hurones', 47),
('Los Hurones Sable Oscuro son sociables y pueden disfrutar de la interacción humana, así que dedica tiempo a jugar y acariciar con ellos.', 'Adulto', 1.2, 'Alimento específico para hurones', 48),
('Los Hurones Panda Chocolate tienen una combinación única de colores en su pelaje que requiere cuidado regular para mantenerse limpio y libre de enredos, así que cepíllalos regularmente y observa cualquier signo de problemas de piel.', 'Adulto', 1.3, 'Alimento específico para hurones', 49),
('Los Hurones Blanco Sable son curiosos y pueden disfrutar de juguetes que despierten su interés, como túneles y pelotas de juguete.', 'Adulto', 1.1, 'Alimento específico para hurones', 50),
-- Consejos para razas de Tortuga
('Las Tortugas Griegas son omnívoras y necesitan una dieta equilibrada que incluya tanto alimentos vegetales como proteínas.', 'Adulto', 0.5, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 51),
('Las Tortugas Rusas son terrestres y necesitan un ambiente seco con acceso a áreas de sombra y refugio.', 'Adulto', 0.3, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 52),
('Las Tortugas Leopardo son activas y necesitan mucho espacio para moverse, así que proporciona un recinto grande y enriquecido.', 'Adulto', 0.6, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 53),
('Las Tortugas Africanas son herbívoras y necesitan una dieta rica en fibra y bajo en proteínas, así que proporciona heno de calidad y vegetales frescos.', 'Adulto', 0.8, 'Vegetales de hojas verdes, heno de alta calidad y frutas', 54),
('Las Tortugas Pavo Real son semiacuáticas y necesitan un ambiente que incluya tanto agua como tierra para salir y secarse.', 'Adulto', 1.0, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 55),
('Las Tortugas Pintadas son omnívoras y necesitan una dieta variada que incluya vegetales, frutas y proteínas.', 'Adulto', 0.7, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 56),
('Las Tortugas de Caja son terrestres y necesitan un refugio seguro para esconderse y descansar, así que proporciona escondites en su recinto.', 'Adulto', 0.4, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 57),
('Las Tortugas de Pescuezo Largo son acuáticas y necesitan un ambiente con acceso a agua profunda para nadar y sumergirse.', 'Adulto', 1.2, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 58),
('Las Tortugas de Orejas Rojas son sociables y pueden disfrutar de la compañía de otras tortugas, así que considera tener más de una en su recinto.', 'Adulto', 0.9, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 59),
('Las Tortugas de Florida son semiacuáticas y necesitan un ambiente que incluya tanto agua como tierra para satisfacer sus necesidades.', 'Adulto', 1.1, 'Vegetales de hojas verdes, frutas y proteínas como gusanos y camarones', 60),

-- Consejos para razas de Iguana
('Las Iguanas Comunes son herbívoras y necesitan una dieta rica en vegetales y hojas verdes, así que proporciona una variedad de alimentos frescos.', 'Adulto', 2.0, 'Vegetales de hojas verdes, frutas y flores', 61),
('Las Iguanas Verdes son activas y necesitan mucho espacio para moverse, así que proporciona un recinto grande y enriquecido con ramas y plantas.', 'Adulto', 2.5, 'Vegetales de hojas verdes, frutas y flores', 62),
('Las Iguanas Rinoceronte son omnívoras y necesitan una dieta variada que incluya tanto vegetales como proteínas, así que proporciona una alimentación equilibrada.', 'Adulto', 2.2, 'Vegetales de hojas verdes, frutas, flores y proteínas como insectos y carne magra', 63),
('Las Iguanas Negras son sensibles a la temperatura y necesitan un ambiente cálido con acceso a áreas de sol y sombra.', 'Adulto', 2.0, 'Vegetales de hojas verdes, frutas y flores', 64),
('Las Iguanas Azules son arbóreas y necesitan un hábitat vertical con ramas y perchas para trepar y explorar.', 'Adulto', 1.8, 'Vegetales de hojas verdes, frutas y flores', 65),
('Las Iguanas Raya Espinosa son omnívoras y necesitan una dieta equilibrada que incluya tanto alimentos vegetales como proteínas.', 'Adulto', 2.3, 'Vegetales de hojas verdes, frutas y flores', 66),
('Las Iguanas Patas de Hacha son activas y necesitan mucho espacio para moverse, así que proporciona un recinto grande y enriquecido con lugares para esconderse.', 'Adulto', 2.4, 'Vegetales de hojas verdes, frutas y flores', 67),
('Las Iguanas Cresta son sociables y pueden disfrutar de la compañía de otras iguanas, así que considera tener más de una en su recinto.', 'Adulto', 2.1, 'Vegetales de hojas verdes, frutas y flores', 68),
('Las Iguanas Caimán son arbóreas y necesitan un hábitat vertical con ramas y perchas para trepar y explorar.', 'Adulto', 1.9, 'Vegetales de hojas verdes, frutas y flores', 69),
('Las Iguanas Escarabajo son omnívoras y necesitan una dieta equilibrada que incluya tanto alimentos vegetales como proteínas.', 'Adulto', 2.2, 'Vegetales de hojas verdes, frutas y flores', 70),

-- Consejos para razas de Pez
('Los Guppy son peces sociales y pueden disfrutar de la compañía de otros peces en un acuario comunitario, así que considera tenerlos en grupos.', 'Adulto', 0.02, 'Alimento en escamas y alimentos congelados o liofilizados', 71),
('Los Bettas son peces solitarios y pueden ser agresivos con otros peces, así que manténlos solos en su propio acuario.', 'Adulto', 0.03, 'Alimento en escamas y alimentos congelados o liofilizados', 72),
('Los Cíclidos son territoriales y pueden necesitar un acuario grande con muchos escondites y áreas de territorio para cada pez.', 'Adulto', 0.05, 'Alimento en escamas y alimentos congelados o liofilizados', 73),
('Los Goldfish son propensos a problemas de vejiga natatoria debido a su forma de nadar, así que evita sobrealimentarlos y asegúrate de que tengan una dieta equilibrada.', 'Adulto', 0.1, 'Alimento en escamas y verduras frescas como guisantes y calabacín', 74),
('Los Neones son peces de cardumen y necesitan vivir en grupos de al menos seis individuos para sentirse seguros y confortables.', 'Adulto', 0.01, 'Alimento en escamas y alimentos congelados o liofilizados', 75),
('Los Koi son peces grandes que necesitan mucho espacio y agua limpia para crecer y prosperar, así que proporciona un estanque grande y bien filtrado.', 'Adulto', 1.0, 'Alimento en escamas y verduras frescas como guisantes y calabacín', 76),
('Los Peces Globo son venenosos y requieren una dieta especializada que incluya alimentos vivos y congelados para satisfacer sus necesidades nutricionales.', 'Adulto', 0.1, 'Alimento específico para peces globo y alimentos vivos como camarones y mejillones', 77),
('Los Killis son peces activos y pueden necesitar un acuario con una tapa segura para evitar que salten fuera del agua.', 'Adulto', 0.02, 'Alimento en escamas y alimentos congelados o liofilizados', 78),
('Las Sardinas son peces de cardumen y necesitan vivir en grupos grandes para sentirse seguros y cómodos, así que considera tenerlos en un acuario comunitario.', 'Adulto', 0.05, 'Alimento en escamas y alimentos congelados o liofilizados', 79),
('Los Peces Ángel son pacíficos y pueden ser compatibles con una variedad de otras especies de peces en un acuario comunitario.', 'Adulto', 0.05, 'Alimento en escamas y alimentos congelados o liofilizados', 80),
-- Consejos para razas de Cobaya
('Las Cobayas Peruvianas tienen pelaje largo que requiere cepillado regular para prevenir enredos y formación de nudos.', 'Adulto', 0.8, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 81),
('Las Cobayas Abisinias tienen un pelaje único en forma de remolino que puede requerir cuidado especial para evitar problemas de piel.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 82),
('Las Cobayas Americanas son activas y necesitan mucho espacio para moverse y explorar, así que proporciona un recinto grande y enriquecido.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 83),
('Las Cobayas Coronet tienen un mechón de pelo en la cabeza que puede necesitar cuidado adicional para evitar enredos y formación de nudos.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 84),
('Las Cobayas Teddy son conocidas por su pelaje denso y esponjoso que puede requerir cepillado regular para mantenerse limpio y libre de enredos.', 'Adulto', 0.8, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 85),
('Las Cobayas Peruvianas de Pelo Corto tienen un pelaje corto pero denso que puede requerir cepillado regular para eliminar el pelo suelto.', 'Adulto', 0.8, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 86),
('Las Cobayas Skinny tienen poco o ningún pelo y pueden ser sensibles al frío, así que asegúrate de mantenerlas abrigadas y cómodas.', 'Adulto', 0.7, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 87),
('Las Cobayas Texel tienen un pelaje rizado y largo que requiere cepillado regular para evitar enredos y formación de bolas de pelo.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 88),
('Las Cobayas Sheltie tienen un pelaje largo y liso que puede requerir cepillado regular para prevenir enredos y formación de nudos.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 89),
('Las Cobayas Peruvianas de Pelo Largo tienen un pelaje largo y sedoso que requiere cepillado regular para mantenerlo limpio y saludable.', 'Adulto', 0.9, 'Heno de alta calidad, verduras frescas y pellets específicos para cobayas', 90),

-- Consejos para razas de Hurón
('Los Hurones Albinos son sensibles a la luz brillante, así que proporciona áreas sombreadas y refugios oscuros en su jaula.', 'Adulto', 1.0, 'Alimento específico para hurones', 91),
('Los Hurones Sable son curiosos y pueden meterse en lugares estrechos, así que asegúrate de que su área de juego esté seguro y libre de peligros.', 'Adulto', 1.2, 'Alimento específico para hurones', 92),
('Los Hurones Blancos son propensos a la obesidad, así que controla su alimentación y proporciona oportunidades para el ejercicio diario.', 'Adulto', 1.1, 'Alimento específico para hurones', 93),
('Los Hurones Chocolate son juguetones y pueden disfrutar de juguetes interactivos y tiempo de juego con sus cuidadores.', 'Adulto', 1.3, 'Alimento específico para hurones', 94),
('Los Hurones Panda tienen un pelaje distintivo que requiere cuidado regular para evitar enredos y problemas de piel, así que cepíllalos con frecuencia.', 'Adulto', 1.2, 'Alimento específico para hurones', 95),
('Los Hurones Polecat son activos y necesitan mucho ejercicio para mantenerse sanos y felices, así que proporciónales oportunidades para correr y explorar.', 'Adulto', 1.1, 'Alimento específico para hurones', 96),
('Los Hurones Canela son curiosos y pueden disfrutar de juguetes que estimulen su mente, como rompecabezas de comida y juguetes de búsqueda.', 'Adulto', 1.0, 'Alimento específico para hurones', 97),
('Los Hurones Sable Oscuro son sociables y pueden disfrutar de la interacción humana, así que dedica tiempo a jugar y acariciar con ellos.', 'Adulto', 1.2, 'Alimento específico para hurones', 98),
('Los Hurones Panda Chocolate tienen una combinación única de colores en su pelaje que requiere cuidado regular para mantenerse limpio y libre de enredos, así que cepíllalos regularmente y observa cualquier signo de problemas de piel.', 'Adulto', 1.3, 'Alimento específico para hurones', 99),
('Los Hurones Blanco Sable son curiosos y pueden disfrutar de juguetes que despierten su interés, como túneles y pelotas de juguete.', 'Adulto', 1.1, 'Alimento específico para hurones', 100);
